#!/usr/bin/env bash
# v8.2 feature suite: sector-launch loadout in Aurelia items, the controllable lumen drone, strict logistics
# conservation, the two overdrive projectors and the prism monolith titan. Official headless server, real jar.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; VENDOR="${VENDOR:-$HOME/.cache/vendor}"
JAVA_HOME="${JAVA_HOME:-$(find "$VENDOR" -maxdepth 1 -type d -name 'jdk-17*' | head -1)}"; JAVA="$JAVA_HOME/bin/java"
TEST="$ROOT/cmdtestrun"; rm -rf "$TEST"; mkdir -p "$TEST/config/mods"; cp "$ROOT/dist/Singularity-v8.3-beta.jar" "$TEST/config/mods/"
cd "$TEST"; mkfifo cmd.fifo
HOME="$TEST" "$JAVA" -Xmx700m -jar "$VENDOR/server-release.jar" <cmd.fifo >server.log 2>&1 & PID=$!; exec 3>cmd.fifo
send(){ echo "$1" >&3; sleep "${2:-2}"; }
P='blackhole-'
sleep 12; send mods 2; send 'config autoPause false' 1
send 'js global.F=function(v,n){var k=Math.pow(10,n);return String(Math.round(Number(v)*k)/k);};global.free=function(cx,cy,rad){for(var r=6;r<120;r+=2)for(var a=0;a<360;a+=10){var q=Vars.world.tileWorld(cx+Math.cos(a/57.3)*r*8,cy+Math.sin(a/57.3)*r*8);if(q==null)continue;var ok=true;for(var dx=-rad;dx<=rad&&ok;dx++)for(var dy=-rad;dy<=rad&&ok;dy++){var z=Vars.world.tile(q.x+dx,q.y+dy);if(z==null||z.solid()||z.floor().isDeep()||z.build!=null)ok=false;}if(ok)return q;}return null;};global.flat=function(q,rad){var plate=Vars.content.block("'$P'aurora-plate");for(var dx=-rad;dx<=rad;dx++)for(var dy=-rad;dy<=rad;dy++){var c=Vars.world.tile(q.x+dx,q.y+dy);if(c!=null&&c.build==null){c.setBlock(Blocks.air);c.setFloor(plate);c.setOverlay(Blocks.air);}}};"helpers ready"' 1

send 'host Ancient_Caldera survival' 10
send 'js var p=Vars.content.planet("'$P'aurelia");var sec=p.sectors.get(p.startSector);Vars.logic.reset();Vars.world.loadSector(sec);Vars.state.rules.sector=sec;Vars.logic.play();var c=Vars.state.rules.defaultTeam.core();global.cx=c.x;global.cy=c.y;"sector loaded "+Vars.world.width()+"x"+Vars.world.height()+" core at "+c.tile.x+","+c.tile.y' 12
send 'js Time.setDeltaProvider(function(){return 1;});Vars.state.rules.unitCapVariable=false;Vars.state.rules.unitCap=200;Vars.state.rules.waves=false;"probe state: "+Vars.state.getState()+" paused="+Vars.state.isPaused()+" delta="+global.F(Time.delta,2)' 2

# ---- 8.2-1: the new content exists, is Aurelia-only, priced in Aurelia items, researched, named
send 'js var names=["lumen-accelerator","prism-overcharger"];var p=Vars.content.planet("'$P'aurelia");var s="",bad=[];names.forEach(function(n){var b=Vars.content.block("'$P'"+n);if(b==null){bad.push(n+":Missing");return;}if(!b.isOnPlanet(p))bad.push(n+":not on aurelia");if(!b.databaseTabs.contains(p))bad.push(n+":no database tab");var node=TechTree.all.find(function(t){return t.content==b;});if(node==null)bad.push(n+":no tech node");else{var c=0;node.requirements.forEach(function(q){c+=q.amount;});if(c==0)bad.push(n+":free node");}b.requirements.forEach(function(q){if(!q.item.name.startsWith("'$P'"))bad.push(n+":VANILLA:"+q.item.name);});if(b.localizedName.indexOf("???")>=0||b.localizedName==b.name)bad.push(n+":raw name");if(b.description==null||b.description.indexOf("???")>=0)bad.push(n+":raw desc");s+=" "+n+"["+b.size+"x"+b.size+" "+b.category+" hp"+b.health+" "+b.requirements.map(function(q){return q.item.name.substring(10)+"x"+q.amount}).toString(",")+"]";});"v8.2 blocks:"+s+(bad.length?" BAD "+bad.join(" "):" -> present, aurelia priced, researched, named")' 3

send 'js var u=Vars.content.unit("'$P'prism-monolith");var p=Vars.content.planet("'$P'aurelia");var bad=[];if(u==null)bad.push("missing");else{if(!u.isOnPlanet(p))bad.push("not on aurelia");if(!u.databaseTabs.contains(p))bad.push("no database tab");var node=TechTree.all.find(function(t){return t.content==u;});if(node==null)bad.push("no tech node");else{var c=0;node.requirements.forEach(function(q){c+=q.amount;});if(c==0)bad.push("free node");}if(u.localizedName.indexOf("???")>=0)bad.push("raw name");if(u.description.indexOf("???")>=0)bad.push("raw desc");}var fab=Vars.content.block("'$P'aurelia-fabricator");var plan=fab.plans.find(function(pl){return pl.unit==u;});if(plan==null)bad.push("NOT BUILDABLE");"v8.2 titan: "+u.localizedName+" hp="+u.health+" armor="+u.armor+" speed="+global.F(u.speed,2)+" hitSize="+u.hitSize+" range="+global.F(u.range,0)+" rotateSpeed="+global.F(u.rotateSpeed,2)+" weapons="+u.weapons.size+" abilities="+u.abilities.size+" flying="+u.flying+" targetAir="+u.targetAir+(plan!=null?" plan="+global.F(plan.time/60,0)+"s "+plan.requirements.map(function(q){return q.item.name.substring(10)+"x"+q.amount}).toString(","):"")+(bad.length?" BAD "+bad.join(" "):" -> ok")' 3

# ---- 8.2-2: the titan is not stronger than the detainer, and has a real upper bound
send 'js var m=Vars.content.unit("'$P'prism-monolith");var d=Vars.content.unit("'$P'astro-detainer");var dps=function(u){var t=0;u.weapons.each(function(w){if(w.bullet==null)return;var dmg=w.bullet.damage+w.bullet.splashDamage;t+=dmg*w.shoot.shots*60/Math.max(w.reload,1);});return t;};"v8.2 balance: monolith hp="+m.health+" armor="+m.armor+" rawDps="+global.F(dps(m),0)+" | detainer hp="+d.health+" armor="+d.armor+" rawDps="+global.F(dps(d),0)+((m.health<d.health&&dps(m)<dps(d))?" -> titan sits under the detainer":" BAD titan outclasses the detainer")' 3

# ---- 8.2-3: the vented lance really locks out. Spawn the titan, give it a target, count shots over 20s.
send 'js var t=Vars.state.rules.defaultTeam;var q=global.free(global.cx,global.cy,10);global.flat(q,16);var m=Vars.content.unit("'$P'prism-monolith");var u=m.create(t);u.set(q.worldx(),q.worldy());u.add();global.mono=u;var e=Vars.content.unit("'$P'lumen-drone").create(Vars.state.rules.waveTeam);e.set(q.worldx()+120,q.worldy());e.health=1000000;e.add();global.foe=e;u.controller(extend(AIController,{updateUnit:function(){}}));"v8.2 titan spawned: hp="+u.health+" at "+global.F(u.x/8,0)+","+global.F(u.y/8,0)+" target at "+global.F(e.x/8,0)+","+global.F(e.y/8,0)+" mounts="+u.mounts.length' 3
send 'js var u=global.mono,e=global.foe;var s0=u.mounts[0].totalShots;var marks=[];for(var k=0;k<1200;k++){e.health=1000000;u.lookAt(u.angleTo(e));u.aim(e.x,e.y);u.controlWeapons(true,true);u.update();if(k%150==0)marks.push(k+":"+(u.mounts[0].totalShots-s0));}var tot=u.mounts[0].totalShots-s0;"v8.2 lance vent: shots over 1200 ticks="+tot+" trace["+marks.join(" ")+"] "+((tot>=4&&tot<=14)?" -> fires in bursts, vents between them (bounded)":" BAD unbounded or silent")' 6
send 'js var u=global.mono,e=global.foe;var p0=u.mounts[1].totalShots+u.mounts[2].totalShots;for(var k=0;k<300;k++){e.health=1000000;u.aim(e.x,e.y);u.controlWeapons(true,true);u.update();}"v8.2 air pods: shots over 300 ticks="+(u.mounts[1].totalShots+u.mounts[2].totalShots-p0)+" (both shoulder pods live)"' 4

# ---- 8.2-4: the overdrive projectors boost, and the boost is capped
send 'js var t=Vars.state.rules.defaultTeam;var q=global.free(global.cx,global.cy,8);global.flat(q,10);var drill=Vars.content.block("'$P'prism-press");var tl=Vars.world.tile(q.x+6,q.y);tl.setNet(drill,t,0);global.vic=tl.build;var a=Vars.world.tile(q.x,q.y);a.setNet(Vars.content.block("'$P'lumen-accelerator"),t,0);global.acc=a.build;var base=global.vic.timeScale();for(var k=0;k<200;k++){global.acc.power.status=1;global.acc.update();global.vic.update();}"v8.2 accelerator: victim="+global.vic.block.name.substring(10)+" baseScale="+global.F(base,2)+" boosted="+global.F(global.vic.timeScale(),2)+" range="+global.F(Vars.content.block("'$P'lumen-accelerator").range/8,1)+" tiles"' 4
send 'js var t=Vars.state.rules.defaultTeam;var q=Vars.world.tile(global.vic.tile.x+6,global.vic.tile.y);global.flat(q,8);var o=Vars.world.tile(q.x+2,q.y);o.setNet(Vars.content.block("'$P'prism-overcharger"),t,0);global.ovc=o.build;for(var k=0;k<300;k++){global.acc.power.status=1;global.acc.update();global.ovc.power.status=1;global.ovc.update();global.vic.update();}var cap=Vars.content.block("'$P'prism-overcharger").speedBoost+Vars.content.block("'$P'prism-overcharger").speedBoostPhase;"v8.2 overcharger: stacked scale="+global.F(global.vic.timeScale(),2)+" hard cap="+global.F(cap,2)+((global.vic.timeScale()<=cap+0.01)?" -> capped, projectors do not stack past the ceiling":" BAD boost exceeds the cap")' 4

# ---- 8.2-5: the lumen hauler is player/logic controllable and commandable, and goes back to hauling
send 'js var u=Vars.content.unit("'$P'lumen-hauler");"v8.2 drone flags: playerControllable="+u.playerControllable+" logicControllable="+u.logicControllable+" allowChangeCommands="+u.allowChangeCommands+" commands="+u.commands.size+((u.playerControllable&&u.logicControllable)?" -> controllable":" BAD not controllable")' 3
send 'js var t=Vars.state.rules.defaultTeam;var q=global.free(global.cx,global.cy,8);global.flat(q,14);global.hx=q.x;global.hy=q.y;q.setNet(Vars.content.block("'$P'lumen-cargo-station"),t,0);var b=q.build;var n=0;while(b.drones.size<1&&n<4000){b.power.status=1;b.update();n++;}global.hub=b;var d=b.drones.get(0);"v8.2 hub drone: "+d.type.name.substring(10)+" controller="+d.controller().getClass().getSimpleName()+" commandable="+d.isCommandable()+((d.isCommandable())?" -> can be selected and ordered":" BAD not commandable")' 5
send 'js var d=global.hub.drones.get(0);var ai=d.controller();var tx=d.x+8*22,ty=d.y+8*10;ai.commandPosition(new Vec2(tx,ty));var d0=Mathf.dst(d.x,d.y,tx,ty);var best=d0;for(var k=0;k<600;k++){global.hub.power.status=1;global.hub.update();d.update();var dd=Mathf.dst(d.x,d.y,tx,ty);if(dd<best)best=dd;}"v8.2 drone order: ordered "+global.F(d0/8,1)+" tiles away, closest approach "+global.F(best/8,1)+" tiles, back home at "+global.F(Mathf.dst(d.x,d.y,tx,ty)/8,1)+" tiles, controller="+d.controller().getClass().getSimpleName()+((best<24)?" -> flew to the ordered point, then returned to hauling":" BAD ignored the order")' 5
send 'js var d=global.hub.drones.get(0);d.controller().clearCommands();for(var k=0;k<400;k++){global.hub.power.status=1;global.hub.update();d.update();}"v8.2 drone release: controller="+d.controller().getClass().getSimpleName()+" carrying="+(d.hasItem()?d.stack.amount:0)+((d.controller().getClass().getSimpleName()=="PorterAI")?" -> back on the logistics network":" BAD stuck idle")' 4

# ---- 8.2-6: strict conservation. Fill the network, haul, then rip the hub out and count every item.
send 'js var t=Vars.state.rules.defaultTeam;var sp=Vars.world.tile(global.hx+9,global.hy);sp.setNet(Vars.content.block("'$P'lumen-supply-post"),t,0);var sb=sp.build;sb.items.add(Vars.content.item("'$P'lumenite"),120);var vt=Vars.world.tile(global.hx-9,global.hy+4);vt.setNet(Vars.content.block("'$P'lumen-logistics-vault"),t,0);global.sb=sb;global.vb=vt.build;global.count=function(){var n=0;if(global.sb.isValid())n+=global.sb.items.total();if(global.vb.isValid())n+=global.vb.items.total();if(global.hub.isValid())n+=global.hub.items.total();Groups.unit.each(function(u){if(u.team==Vars.state.rules.defaultTeam&&u.hasItem())n+=u.stack.amount;});return n;};global.total0=global.count();"v8.2 conservation start: total items in the network="+global.total0' 4
send 'js for(var k=0;k<1800;k++){global.hub.power.status=1;global.hub.update();global.sb.update();global.vb.update();Groups.unit.each(function(u){if(u.team==Vars.state.rules.defaultTeam)u.update();});}"v8.2 conservation after 30s: total="+global.count()+" (start "+global.total0+") supply="+global.sb.items.total()+" vault="+global.vb.items.total()+" hub="+global.hub.items.total()+" dispatched="+global.hub.dispatched+((global.count()==global.total0)?" -> nothing created, nothing voided":" BAD item count changed")' 6
send 'js var before=global.count();global.hub.tile.setNet(Blocks.air,Vars.state.rules.defaultTeam,0);for(var k=0;k<200;k++){global.sb.update();global.vb.update();Groups.unit.each(function(u){if(u.team==Vars.state.rules.defaultTeam)u.update();});}var after=global.sb.items.total()+global.vb.items.total()+Vars.state.rules.defaultTeam.core().items.total();"v8.2 hub removed: items before="+before+" accounted after="+(global.sb.items.total()+global.vb.items.total())+" in network (core holds "+Vars.state.rules.defaultTeam.core().items.total()+") "+((global.sb.items.total()+global.vb.items.total())>=before-2?" -> cargo was handed over, not voided":" BAD items vanished with the hub")' 6

# ---- 8.2-7: no infinite loop. A vault beside a request pad must settle instead of bouncing items forever.
send 'js var t=Vars.state.rules.defaultTeam;var q=global.free(global.cx,global.cy,8);global.flat(q,14);q.setNet(Vars.content.block("'$P'lumen-cargo-station"),t,0);var h=q.build;var n=0;while(h.drones.size<1&&n<4000){h.power.status=1;h.update();n++;}global.hub2=h;var vt=Vars.world.tile(q.x+7,q.y);vt.setNet(Vars.content.block("'$P'lumen-logistics-vault"),t,0);var vb=vt.build;vb.items.add(Vars.content.item("'$P'lumenite"),200);var pd=Vars.world.tile(q.x-7,q.y);pd.setNet(Vars.content.block("'$P'lumen-cargo-point"),t,0);var pb=pd.build;pb.configure(Vars.content.item("'$P'lumenite"));global.vb2=vb;global.pb2=pb;"v8.2 loop probe: vault "+vb.items.total()+", request pad asking for "+(pb.sought==null?"nothing":pb.sought.name.substring(10))' 4
send 'js var marks=[];for(var r=0;r<6;r++){for(var k=0;k<600;k++){global.hub2.power.status=1;global.hub2.update();global.vb2.update();global.pb2.update();Groups.unit.each(function(u){if(u.team==Vars.state.rules.defaultTeam)u.update();});}marks.push(global.hub2.dispatched);}var deltas=[];for(var i=1;i<marks.length;i++)deltas.push(marks[i]-marks[i-1]);var last=deltas[deltas.length-1];"v8.2 loop check: dispatch counts per 10s ["+marks.join(" ")+"] deltas ["+deltas.join(" ")+"] vault="+global.vb2.items.total()+" pad="+global.pb2.items.total()+((last<=2)?" -> the network settles, no endless shuttling":" BAD still dispatching in a loop")' 10

# ---- 8.2-8: launching to another sector is paid for in Aurelia items
send 'js if(Vars.schematics==null){Vars.schematics=new Packages.mindustry.game.Schematics();Vars.schematics.loadSync();}var CL=Vars.content.block("'$P'aurelia-core").getClass().getClassLoader();var K=CL.loadClass("blackhole.AureliaLaunch");K.getMethod("install").invoke(null);var core=Vars.content.block("'$P'aurelia-core");var seq=Vars.schematics.getLoadouts(core);var bad=[];if(seq==null||seq.size==0){bad.push("no loadout registered");}else{seq.get(0).requirements().each(function(it,amt){if(amt>0&&!it.name.startsWith("'$P'"))bad.push("VANILLA:"+it.name);});}var sel=Vars.universe.getLoadout(core);if(sel==null)bad.push("universe has no loadout");var cost=[];if(sel!=null)sel.requirements().each(function(it,amt){if(amt>0)cost.push(it.name.substring(10)+"x"+amt);});"v8.2 launch loadout: registered="+(seq==null?0:seq.size)+" schematic(s), universe picks "+(sel==null?"none":sel.name())+" costing ["+cost.join(" ")+"] valid="+K.getMethod("valid").invoke(null)+(bad.length?" BAD "+bad.join(" "):" -> paid for in Aurelia resources")' 5
send 'js var seqv=new Packages.mindustry.type.ItemSeq();seqv.add(Vars.content.item("copper"),300);seqv.add(Vars.content.item("'$P'lumenite"),200);Vars.universe.updateLaunchResources(seqv);var CL=Vars.content.block("'$P'aurelia-core").getClass().getClassLoader();var K=CL.loadClass("blackhole.AureliaLaunch");K.getMethod("sanitizeLaunchResources").invoke(null);var res=Vars.universe.getLaunchResources();var bad=[],list=[];res.each(function(it,amt){if(amt>0){list.push(it.name+"x"+amt);if(!it.name.startsWith("'$P'"))bad.push("VANILLA launch resource:"+it.name);}});"v8.2 launch payload cleanup: carried=["+list.join(" ")+"]"+(bad.length?" BAD "+bad.join(" "):" -> vanilla items are stripped from the Aurelia launch payload")' 4
send 'js var p=Vars.content.planet("'$P'aurelia");var shown=[],van=0;Vars.content.items().each(function(it){if(it.isOnPlanet(p)){shown.push(it.name.substring(10));if(!it.name.startsWith("'$P'"))van++;}});"v8.2 launch items offered on aurelia="+shown.length+" ["+shown.slice(0,6).join(" ")+"...] vanilla among them="+van' 4

# ---- 8.2-9: full text audit over everything this jar owns
send 'js var miss=[];var n=0;Vars.content.getContentMap().forEach(function(arr){arr.each(function(c){if(c instanceof UnlockableContent&&c.minfo!=null&&c.minfo.mod!=null&&c.minfo.mod.name=="blackhole"){n++;var ln=c.localizedName,d=c.description;if(ln==null||ln.indexOf("???")>=0||ln==c.name)miss.push(c.name+":name");if(d==null||d.indexOf("???")>=0||d.length<4)miss.push(c.name+":desc");}});});"v8.2 text audit: "+n+" own content, missing/raw="+miss.length+(miss.length?" BAD "+miss.slice(0,10).join(" "):"")' 5

send 'exit' 3
sleep 3; kill $PID 2>/dev/null; wait $PID 2>/dev/null
echo "================ RESULTS ================"
grep -aE "v8\.2|BAD|Exception|EcmaError|Error:" server.log | sed 's/\x1b\[[0-9;]*m//g'
echo "================ VERDICT ================"
if grep -aqE "BAD |Exception|EcmaError|Error:|NOT BUILDABLE|VANILLA" server.log; then echo "CMDTEST FAILED"; exit 1; else echo "CMDTEST PASSED: Singularity v8.3-beta command suite"; exit 0; fi
