#!/usr/bin/env bash
# v8.1 feature suite: the drone logistics network, the liquid tier, the gates, the lattice nerf, the detainer
# description fix and the three new units. Boots the official headless server with the real jar.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"; VENDOR="${VENDOR:-$HOME/.cache/vendor}"
JAVA_HOME="${JAVA_HOME:-$(find "$VENDOR" -maxdepth 1 -type d -name 'jdk-17*' | head -1)}"; JAVA="$JAVA_HOME/bin/java"
TEST="$ROOT/logitestrun"; rm -rf "$TEST"; mkdir -p "$TEST/config/mods"; cp "$ROOT/dist/Singularity-v8.3-beta.jar" "$TEST/config/mods/"
cd "$TEST"; mkfifo cmd.fifo
HOME="$TEST" "$JAVA" -Xmx700m -jar "$VENDOR/server-release.jar" <cmd.fifo >server.log 2>&1 & PID=$!; exec 3>cmd.fifo
send(){ echo "$1" >&3; sleep "${2:-2}"; }
P='blackhole-'
sleep 12; send mods 2; send 'config autoPause false' 1
send 'js global.F=function(v,n){var k=Math.pow(10,n);return String(Math.round(Number(v)*k)/k);};global.free=function(cx,cy,rad){for(var r=6;r<120;r+=2)for(var a=0;a<360;a+=10){var q=Vars.world.tileWorld(cx+Math.cos(a/57.3)*r*8,cy+Math.sin(a/57.3)*r*8);if(q==null)continue;var ok=true;for(var dx=-rad;dx<=rad&&ok;dx++)for(var dy=-rad;dy<=rad&&ok;dy++){var z=Vars.world.tile(q.x+dx,q.y+dy);if(z==null||z.solid()||z.floor().isDeep()||z.build!=null)ok=false;}if(ok)return q;}return null;};"helpers ready"' 1

# ---- boot a campaign sector and make the world deterministic
send 'host Ancient_Caldera survival' 10
send 'js var p=Vars.content.planet("'$P'aurelia");var sec=p.sectors.get(p.startSector);Vars.logic.reset();Vars.world.loadSector(sec);Vars.state.rules.sector=sec;Vars.logic.play();var c=Vars.state.rules.defaultTeam.core();global.cx=c.x;global.cy=c.y;"sector loaded "+Vars.world.width()+"x"+Vars.world.height()+" core at "+c.tile.x+","+c.tile.y' 12
send 'js Time.setDeltaProvider(function(){return 1;});Vars.state.rules.unitCapVariable=false;Vars.state.rules.unitCap=200;Vars.state.rules.waves=false;"probe state: "+Vars.state.getState()+" paused="+Vars.state.isPaused()+" delta="+global.F(Time.delta,2)+" cap="+Units.getCap(Vars.state.rules.defaultTeam)' 2

# ---- 8.1-1: every new block is real content: on Aurelia, in the database, in the tree, Aurelia priced
send 'js var names=["lumen-supply-post","lumen-buffer-post","lumen-logistics-vault","lumen-liquid-relay","lumen-tank","lumen-reservoir","lumen-overflow-gate","lumen-underflow-gate"];var p=Vars.content.planet("'$P'aurelia");var s="",bad=[];names.forEach(function(n){var b=Vars.content.block("'$P'"+n);if(b==null){bad.push(n+":Missing");return;}if(!b.isOnPlanet(p))bad.push(n+":not on aurelia");if(!b.databaseTabs.contains(p))bad.push(n+":no database tab");var node=TechTree.all.find(function(t){return t.content==b;});if(node==null)bad.push(n+":no tech node");else{var c=0;node.requirements.forEach(function(q){c+=q.amount;});if(c==0)bad.push(n+":free node");}b.requirements.forEach(function(q){if(!q.item.name.startsWith("'$P'"))bad.push(n+":VANILLA:"+q.item.name);});s+=" "+n+"["+b.size+"x"+b.size+" "+b.category+" "+b.requirements.map(function(q){return q.item.name.substring(10)+"x"+q.amount}).toString(",")+"]";});"v8.1 blocks:"+s+(bad.length?" BAD "+bad.join(" "):" -> all present, aurelia priced, researched, in the database")' 2

# ---- 8.1-2: the drone network actually hauls. Hub + supply post (stocked) + request pad (asking for lumenite).
send 'js var t=Vars.state.rules.defaultTeam;var plate=Vars.content.block("'$P'aurora-plate");var q=global.free(global.cx,global.cy,8);for(var dx=-14;dx<=14;dx++)for(var dy=-14;dy<=14;dy++){var c=Vars.world.tile(q.x+dx,q.y+dy);if(c!=null&&c.build==null){c.setBlock(Blocks.air);c.setFloor(plate);c.setOverlay(Blocks.air);}}global.hx=q.x;global.hy=q.y;q.setNet(Vars.content.block("'$P'lumen-cargo-station"),t,0);var b=q.build;var n=0;while(b.drones.size<1&&n<4000){b.power.status=1;b.update();n++;}global.hub=b;"v8.1 hub: built "+b.drones.size+" drone(s) in "+n+" ticks, type="+(b.drones.size>0?b.drones.get(0).type.name.substring(10):"none")+", tethered="+(b.drones.size>0?(b.drones.get(0) instanceof BuildingTetherc):"-")+", controller="+(b.drones.size>0?b.drones.get(0).controller().getClass().getSimpleName():"-")' 4
send 'js var t=Vars.state.rules.defaultTeam;var sp=Vars.world.tile(global.hx+9,global.hy);sp.setNet(Vars.content.block("'$P'lumen-supply-post"),t,0);var sb=sp.build;sb.items.add(Vars.content.item("'$P'lumenite"),120);var pd=Vars.world.tile(global.hx-9,global.hy+4);pd.setNet(Vars.content.block("'$P'lumen-cargo-point"),t,0);var pb=pd.build;pb.configure(Vars.content.item("'$P'lumenite"));global.sb=sb;global.pb=pb;var d=global.hub.drones.get(0);global.dx0=d.x;global.dy0=d.y;global.power=function(n){for(var k=0;k<n;k++){global.hub.power.status=1;global.hub.update();}};global.power(200);"v8.1 network laid out: supply post at "+sp.x+","+sp.y+" with "+sb.items.total()+" lumenite, request pad at "+pd.x+","+pd.y+" asking for "+(pb.sought==null?"nothing":pb.sought.name.substring(10))+", drone at "+global.F(d.x/8,0)+","+global.F(d.y/8,0)' 3
sleep 25
send 'js global.power(120);var d=global.hub.drones.get(0);var ai=d.controller();var moved=Mathf.dst(d.x,d.y,global.dx0,global.dy0);"v8.1 haul after 25s: nodes seen="+global.hub.lastNodes+" requests="+global.hub.lastRequests+", drone moved "+global.F(moved,0)+" world units, carrying "+(d.stack.amount>0?d.stack.amount+" "+d.item().name.substring(10):"nothing")+", supply post has "+global.sb.items.total()+", request pad has "+global.pb.items.total()+", hub dispatched "+global.hub.dispatched+" hauls"+((moved>4&&global.pb.items.total()>0&&global.hub.dispatched>0)?" -> the drones transport":" BAD drones idle")' 3
sleep 20
send 'js global.power(120);"v8.1 haul after 45s: supply post "+global.sb.items.total()+" left, request pad holds "+global.pb.items.total()+", hub dispatched "+global.hub.dispatched+" hauls, drones="+global.hub.drones.size' 3

# ---- 8.1-3: storage is served before a passive provider, and surplus in the hub is parked in the vault
send 'js var t=Vars.state.rules.defaultTeam;var v=Vars.world.tile(global.hx+4,global.hy-9);v.setNet(Vars.content.block("'$P'lumen-logistics-vault"),t,0);global.vb=v.build;global.hub.items.add(Vars.content.item("'$P'aurite"),90);global.power(200);"v8.1 vault placed at "+v.x+","+v.y+", hub stocked with 90 surplus aurite, vault holds "+global.vb.items.total()' 3
sleep 22
send 'js global.power(200);"v8.1 surplus: hub holds "+global.hub.items.total()+", vault holds "+global.vb.items.total()+" ("+(global.vb.items.get(Vars.content.item("'$P'aurite"))|0)+" aurite), dispatched "+global.hub.dispatched+((global.vb.items.total()>0)?" -> active provider pushes surplus into storage":" BAD surplus not moved")' 3

# ---- 8.1-4: a free hauler joins the nearest hub on its own (auto-assignment)
send 'js var t=Vars.state.rules.defaultTeam;var ty=Vars.content.unit("'$P'lumen-hauler");var u=ty.spawn(t,(global.hx+16)*8,(global.hy+16)*8);global.hl=u;"v8.1 hauler spawned unattached: controller="+u.controller().getClass().getSimpleName()+" home="+(u.controller().home==null?"none":"set")+" cap="+ty.itemCapacity' 3
sleep 12
send 'js global.power(60);var u=global.hl;var ai=u.controller();"v8.1 hauler adoption: home="+(ai.home==null?"NONE":ai.home.block.name.substring(10)+" at "+ai.home.tile.x+","+ai.home.tile.y)+", hub drone list="+global.hub.drones.size+((ai.home!=null)?" -> a stray hauler is adopted by the nearest hub":" BAD not adopted")' 3

# ---- 8.1-5: the wireless liquid relay levels liquid across a gap no conduit crosses
send 'js var t=Vars.state.rules.defaultTeam;var a=Vars.world.tile(global.hx,global.hy+12);var b=Vars.world.tile(global.hx+16,global.hy+12);var plate=Vars.content.block("'$P'aurora-plate");[a,b].forEach(function(q){for(var dx=-2;dx<=2;dx++)for(var dy=-2;dy<=2;dy++){var c=Vars.world.tile(q.x+dx,q.y+dy);if(c!=null&&c.build==null){c.setBlock(Blocks.air);c.setFloor(plate);}}});a.setNet(Vars.content.block("'$P'lumen-liquid-relay"),t,0);b.setNet(Vars.content.block("'$P'lumen-liquid-relay"),t,0);var ab=a.build,bb=b.build;ab.liquids.add(Vars.content.liquid("'$P'tidewater"),300);var n=0;while(bb.liquids.currentAmount()<1&&n<3000){ab.update();bb.update();n++;}"v8.1 liquid relay: distance "+global.F(Mathf.dst(a.x,a.y,b.x,b.y),0)+" tiles with no pipe, source "+global.F(ab.liquids.currentAmount(),0)+", far relay received "+global.F(bb.liquids.currentAmount(),0)+" after "+n+" ticks, links="+ab.links.size+((bb.liquids.currentAmount()>0)?" -> wireless liquid transport works":" BAD nothing moved");' 4
send 'js var t=Vars.state.rules.defaultTeam;var s=Vars.content.block("'$P'lumen-tank"),l=Vars.content.block("'$P'lumen-reservoir");"v8.1 liquid stores: tank "+s.size+"x"+s.size+" "+global.F(s.liquidCapacity,0)+" units, reservoir "+l.size+"x"+l.size+" "+global.F(l.liquidCapacity,0)+" units ("+global.F(l.liquidCapacity/s.liquidCapacity,1)+"x)"' 2

# ---- 8.1-6: both gates behave like vanilla - the overflow gate only sidesteps when the front is full
send 'js var o=Vars.content.block("'$P'lumen-overflow-gate"),u=Vars.content.block("'$P'lumen-underflow-gate");"v8.1 gates: overflow invert="+o.invert+" class="+o.getClass().getSuperclass().getSimpleName()+", underflow invert="+u.invert+" -> vanilla overflow mechanics, both 3D"' 2
send 'js var t=Vars.state.rules.defaultTeam;var g=Vars.world.tile(global.hx-4,global.hy-12);var plate=Vars.content.block("'$P'aurora-plate");for(var dx=-3;dx<=3;dx++)for(var dy=-3;dy<=3;dy++){var c=Vars.world.tile(g.x+dx,g.y+dy);if(c!=null&&c.build==null){c.setBlock(Blocks.air);c.setFloor(plate);}}g.setNet(Vars.content.block("'$P'lumen-overflow-gate"),t,0);var gb=g.build;var side=Vars.world.tile(g.x,g.y+1);side.setNet(Vars.content.block("'$P'lumen-cargo-point"),t,0);var sbb=side.build;sbb.configure(Vars.content.item("'$P'lumenite"));var it=Vars.content.item("'$P'lumenite");var core=Vars.state.rules.defaultTeam.core();var ok=gb.acceptItem(core,it);gb.handleItem(core,it);var n=0;while(n<200){gb.update();n++;}"v8.1 overflow gate live: accepts="+ok+", items held="+gb.items.total()+" -> it passes rather than hoards";' 3

# ---- 8.1-7: the lattice nerf - a bounded absorber with an overload and a wave lockout
send 'js var blk=Vars.content.block("'$P'aegis-lattice");"v8.1 lattice stats: bank="+global.F(blk.capacity,0)+", intake ceiling="+global.F(blk.heatCeiling,0)+", cooling "+global.F(blk.coolRate,0)+"/s, overload downtime "+global.F(blk.rechargeTime/60,1)+"s, wave lockout "+global.F(blk.waveCooldown/60,1)+"s"' 2
send 'js var t=Vars.state.rules.defaultTeam;var q=global.free(global.cx,global.cy,4);var blk=Vars.content.block("'$P'aegis-lattice");q.setNet(blk,t,0);var b=q.build;b.warmup=1;var bt=Vars.content.unit("'$P'shard-rover").weapons.get(0).bullet;var foe=Vars.content.unit("'$P'shard-rover").spawn(Vars.state.rules.waveTeam,q.worldx()+150,q.worldy());foe.controller(extend(AIController,{updateUnit:function(){}}));var fired=0,n=0,waves=0,bank0=0;while(b.inert<=0&&n<4000){for(var i=0;i<3;i++){bt.create(foe,Vars.state.rules.waveTeam,q.worldx()+20,q.worldy()+(i*4-4),180);fired++;}Groups.bullet.update();Groups.bullet.updatePhysics();var before=b.bank;b.warmup=1;b.update();if(b.bank<before-10)waves++;Groups.bullet.each(function(bu){bu.remove();});Groups.bullet.update();n++;}var inert=b.inert;var m=0;while(b.inert>0&&m<2000){b.warmup=1;b.update();m++;}foe.kill();var res="v8.1 lattice nerf: took "+fired+" shots in "+n+" ticks, "+waves+" discharge(s) -> field collapsed (downtime "+global.F(inert,0)+" ticks), recovered after "+m+" ticks, fieldUp now="+b.fieldUp()+((n<4000&&m>0)?" -> bounded, it can no longer tank forever":" BAD no ceiling");b.tile.setNet(Blocks.air);res' 8

# ---- 8.1-8: the detainer shows a real purpose, and no content anywhere shows a raw key or a class name
send 'js var u=Vars.content.unit("'$P'astro-detainer");var ab=[];u.abilities.each(function(a){ab.push(a.getClass().getSimpleName()+"->\""+a.localized()+"\"");});"v8.1 detainer: name=\""+u.localizedName+"\" description=\""+(u.description==null?"NULL":u.description.substring(0,60))+"...\" details="+(u.details==null?"none":"\""+u.details.substring(0,40)+"...\"")+" abilities: "+ab.join(" ")+((u.description!=null&&u.description.indexOf("@")!=0&&u.description.indexOf("???")<0)?" -> real text, not a key":" BAD raw key")' 2
send 'js var bad=[],n=0;[Vars.content.blocks(),Vars.content.units(),Vars.content.items(),Vars.content.liquids()].forEach(function(l){l.each(function(c){if(!c.name.startsWith("'$P'"))return;n++;var nm=c.localizedName,ds=c.description;if(nm==null||nm.indexOf("???")>=0||nm==c.name)bad.push(c.name.substring(10)+":name");if(ds==null||ds.length<4||ds.indexOf("???")>=0||ds.charAt(0)=="@")bad.push(c.name.substring(10)+":desc");});});var abad=[];Vars.content.units().each(function(t){if(!t.name.startsWith("'$P'"))return;t.abilities.each(function(a){var s=a.localized();if(s==null||s.indexOf("???")>=0||s==a.getClass().getSimpleName())abad.push(t.name.substring(10)+":"+a.getClass().getSimpleName());});});"v8.1 text audit: "+n+" own content checked, missing/raw names or descriptions="+bad.length+(bad.length?" BAD "+bad.slice(0,12).join(" "):"")+", abilities showing a class name="+abad.length+(abad.length?" BAD "+abad.slice(0,8).join(" "):" -> every ability is named")' 3
send 'js var f=Vars.content.block("'$P'astro-fabricator");"v8.1 rename: astro-fabricator is now \""+f.localizedName+"\""+((f.localizedName.indexOf("流明")>=0||f.localizedName.indexOf("Lumen")>=0)?" -> renamed":" BAD old name")' 2

# ---- 8.1-9: the three new units are printable, researched, and alive
send 'js var f=Vars.content.block("'$P'aurelia-fabricator"),d=Vars.content.block("'$P'tide-dock");var want=[["lumen-hauler",f],["aurite-vanguard",f],["tide-tender",d]];var bad=[],s="";want.forEach(function(w){var u=Vars.content.unit("'$P'"+w[0]);if(u==null){bad.push(w[0]+":Missing");return;}var pl=null;for(var i=0;i<w[1].plans.size;i++)if(w[1].plans.get(i).unit==u)pl=w[1].plans.get(i);if(pl==null)bad.push(w[0]+":not printable");var node=TechTree.all.find(function(t){return t.content==u;});if(node==null)bad.push(w[0]+":no tech node");s+=" "+w[0]+"[hp "+global.F(u.health,0)+" "+(pl!=null?global.F(pl.time/60,0)+"s in "+w[1].name.substring(10):"-")+"]";});"v8.1 new units:"+s+(bad.length?" BAD "+bad.join(" "):" -> all three printable and researched")' 2
send 'js var t=Vars.state.rules.defaultTeam;var s="";["aurite-vanguard","lumen-hauler"].forEach(function(n){var ty=Vars.content.unit("'$P'"+n);var sp=global.free(global.cx,global.cy,3);var u=ty.spawn(t,sp.worldx(),sp.worldy());u.controller(extend(AIController,{updateUnit:function(){}}));var x0=u.x,y0=u.y;var v=new Vec2();for(var k=0;k<120;k++){v.trns(45,u.speed());u.moveAt(v);u.lookAt(45);u.aim(u.x+90,u.y+90);u.controlWeapons(true,true);u.update();}var sh=0;for(var m=0;m<u.mounts.length;m++)sh+=u.mounts[m].totalShots;s+=n+"[moved "+global.F(Mathf.dst(u.x,u.y,x0,y0),0)+" shots "+sh+" hp "+global.F(u.health,0)+(u.dead?" DEAD":"")+"] ";u.kill();});"v8.1 new units live: "+s' 5
send 'js var t=Vars.state.rules.defaultTeam;var w=null;Vars.world.tiles.eachTile(function(q){if(w==null&&q.floor().isLiquid&&q.build==null&&!q.solid())w=q;});var ty=Vars.content.unit("'$P'tide-tender");var u=ty.spawn(t,w.worldx(),w.worldy());u.controller(extend(AIController,{updateUnit:function(){}}));for(var k=0;k<60;k++){u.aim(u.x+60,u.y+60);u.controlWeapons(true,true);u.update();}var sh=0;for(var m=0;m<u.mounts.length;m++)sh+=u.mounts[m].totalShots;var res="v8.1 tide tender: naval="+ty.naval+" on "+u.floorOn().name.substring(10)+" shots "+sh+(u.dead?" DEAD":" alive");u.kill();res' 4

# ---- 8.1-10: every unit in the mod is still manufacturable somewhere, and the unit count
send 'js var made={};Vars.content.blocks().each(function(b){if(b.plans!=null&&b.plans.size!=undefined){for(var i=0;i<b.plans.size;i++)made[b.plans.get(i).unit.name]=b.name;}});var miss=[],n=0;Vars.content.units().each(function(u){if(!u.name.startsWith("'$P'"))return;n++;if(u.hidden&&made[u.name]==null)return;if(made[u.name]==null)miss.push(u.name.substring(10));});"v8.1 unit audit: "+n+" own units, not printable anywhere="+miss.length+(miss.length?" ("+miss.join(" ")+")":"")+" -> every visible unit has a factory"' 3

send exit 3; exec 3>&-; wait $PID 2>/dev/null
grep -aoE "v8\.1[^\"]*" "$TEST/server.log" | sed 's/\x1b\[[0-9;]*m//g' | sed 's/\\n/ /g' | tail -40
echo "---- exceptions ----"
grep -aE "Exception|error" "$TEST/server.log" | grep -v "errorColor" | head -20 || true
BADS=$(grep -ac "BAD" "$TEST/server.log" || true)
EXC=$(grep -aE "Exception" "$TEST/server.log" | grep -vc "errorColor" || true)
if [ "$BADS" = "0" ] && [ "$EXC" = "0" ]; then
  echo "LOGITEST PASSED: Singularity v8.3-beta logistics suite"; exit 0
else
  echo "LOGITEST FAILED: $BADS bad probe line(s), $EXC exception(s)"; exit 1
fi
