from pathlib import Path
root=Path(__file__).resolve().parents[1]
en=r'''\n# v6 Aurelia expedition\nplanet.blackhole-aurelia.name = Aurelia\nplanet.blackhole-aurelia.description = A pale, fractured expedition world. Its buried resonance beds must be stabilized and arranged into a harmonic field before its highest technology can be made.\nitem.blackhole-lumenite.name = Lumenite\nitem.blackhole-lumenite.description = Blue-white crystalline ore mined from Aurelia's plate fields.\nitem.blackhole-resonance-shard.name = Resonance Shard\nitem.blackhole-resonance-shard.description = A stabilized fragment emitted by a defended Rift Anchor. It cannot be manufactured in an ordinary factory.\nitem.blackhole-prism-alloy.name = Prism Alloy\nitem.blackhole-prism-alloy.description = Reflective structural alloy pressed from Lumenite and Resonance Shards.\nitem.blackhole-concord-core.name = Concord Core\nitem.blackhole-concord-core.description = A rare coordination core emitted only when three stabilized Rift Anchors harmonize around one Relay.\nblock.blackhole-aurelia-core.name = Aurelia Core\nblock.blackhole-aurelia-core.description = Expedition command core for the Aurelia campaign.\nblock.blackhole-rift-anchor.name = Rift Anchor\nblock.blackhole-rift-anchor.description = Place only on a natural Resonance Bed. With power and no enemies nearby, it stabilizes the rift and periodically emits Resonance Shards. Losing the area drains its progress rather than destroying it.\nblock.blackhole-harmonic-relay.name = Harmonic Relay\nblock.blackhole-harmonic-relay.description = A spatial network device, not a factory. Place it within range of three defended, stabilized Rift Anchors to synthesize Concord Cores.\nblock.blackhole-prism-press.name = Prism Press\nblock.blackhole-prism-press.description = Presses Lumenite and field-earned Resonance Shards into Prism Alloy.\nblock.blackhole-concord-synthesizer.name = Concord Synthesizer\nblock.blackhole-concord-synthesizer.description = Supplements field-made Concord Cores for late Aurelia production.\nblock.blackhole-aurelia-fabricator.name = Aurelia Fabricator\nblock.blackhole-aurelia-fabricator.description = Builds Aurelia expedition drones and shielded guards.\nblock.blackhole-prism-pylon.name = Prism Pylon\nblock.blackhole-prism-pylon.description = Long-range piercing power turret for defending rift expeditions.\nblock.blackhole-arc-mortar.name = Arc Mortar\nblock.blackhole-arc-mortar.description = Heavy indirect-fire power turret fueled by Concord technology.\nunit.blackhole-glint.name = Glint\nunit.blackhole-glint.description = Fast Aurelia reconnaissance drone.\nunit.blackhole-aurora-guard.name = Aurora Guard\nunit.blackhole-aurora-guard.description = Shielded expedition guard with paired prism lances.\nunit.blackhole-astral-aegis.description = An original white, silver and cyan mobile suit: a true two-legged mech with a crest, visor, folding wings and halo. It fires a white-plasma rail lance and guided shoulder pods, projects prism shielding and repairs nearby allies.\n'''
zh=r'''\n# v6 欧雷利亚远征\nplanet.blackhole-aurelia.name = 欧雷利亚\nplanet.blackhole-aurelia.description = 一颗苍白破碎的远征行星。必须先守住并稳定地下共振床，再把它们构成谐振场，才能制造最高级的行星科技。\nitem.blackhole-lumenite.name = 流明矿\nitem.blackhole-lumenite.description = 从欧雷利亚板块矿场开采的蓝白晶体矿。\nitem.blackhole-resonance-shard.name = 共振碎片\nitem.blackhole-resonance-shard.description = 由被守住的裂隙锚稳定后放出的碎片，普通工厂无法合成。\nitem.blackhole-prism-alloy.name = 棱晶合金\nitem.blackhole-prism-alloy.description = 由流明矿和共振碎片压制的高反射结构合金。\nitem.blackhole-concord-core.name = 协律核心\nitem.blackhole-concord-core.description = 仅当三座已稳定裂隙锚围绕一台中继器形成谐振时才会产出的稀有协调核心。\nblock.blackhole-aurelia-core.name = 欧雷利亚核心\nblock.blackhole-aurelia-core.description = 欧雷利亚战役的远征指挥核心。\nblock.blackhole-rift-anchor.name = 裂隙锚\nblock.blackhole-rift-anchor.description = 只能放在天然共振床上。供电且周围无敌人时会稳定裂隙，并周期性放出共振碎片；失守只会倒退进度，不会直接摧毁成果。\nblock.blackhole-harmonic-relay.name = 谐振中继器\nblock.blackhole-harmonic-relay.description = 不是工厂，而是空间网络装置。把它置于三座被守住、已稳定裂隙锚范围内，即可合成协律核心。\nblock.blackhole-prism-press.name = 棱晶压机\nblock.blackhole-prism-press.description = 将流明矿和野外获得的共振碎片压制成棱晶合金。\nblock.blackhole-concord-synthesizer.name = 协律合成器\nblock.blackhole-concord-synthesizer.description = 为欧雷利亚后期生产补充协律核心。\nblock.blackhole-aurelia-fabricator.name = 欧雷利亚制造厂\nblock.blackhole-aurelia-fabricator.description = 制造欧雷利亚远征无人机和带盾守卫。\nblock.blackhole-prism-pylon.name = 棱晶塔\nblock.blackhole-prism-pylon.description = 用于保卫裂隙远征的长程穿透能量炮塔。\nblock.blackhole-arc-mortar.name = 弧光迫击炮\nblock.blackhole-arc-mortar.description = 以协律科技驱动的重型间接火力能量炮塔。\nunit.blackhole-glint.name = 微光\nunit.blackhole-glint.description = 快速欧雷利亚侦察无人机。\nunit.blackhole-aurora-guard.name = 极光守卫\nunit.blackhole-aurora-guard.description = 搭载双棱枪与力场盾的远征守卫。\nunit.blackhole-astral-aegis.description = 原创白、银、青配色的真正双足机动战甲：拥有冠饰、面罩、折翼与光环。它使用白等离子轨道长枪和肩部制导舱，投射棱晶护盾并修复附近友军。\n'''
for path,data in [(root/'assets/bundles/bundle.properties',en),(root/'assets/bundles/bundle_zh_CN.properties',zh)]:
    text=path.read_text()
    marker='# v6 Aurelia expedition' if path.name=='bundle.properties' else '# v6 欧雷利亚远征'
    if marker not in text:
        # The compact raw literals above keep this generator easy to maintain; expand
        # their explicit newlines only when materializing the bundle.
        path.write_text(text.rstrip() + "\n" + data.replace("\\n", "\n"))
