#!/usr/bin/env python3
"""Generate the v4.1 Citadel (Titan) animation layers.

The game derives TankUnit tread frames from a vertical 1-pixel strip inside the
base ``*-treads.png`` texture.  These sheets deliberately keep a non-transparent
strip at x=0, which is the strip selected by BHUnits.treadRects.  Therefore the
animation is generated by Mindustry at load time and stays synchronized with
actual movement instead of running while the tank is idle.

Run this script after changing the art:
    python3 tools/gen_titan_animation.py
"""
from __future__ import annotations

import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter

OUT = Path(__file__).resolve().parents[1] / "assets" / "sprites"
OUT.mkdir(parents=True, exist_ok=True)
S = 4

OUTLINE = (18, 14, 24, 255)
DARK = (38, 32, 46, 255)
MID = (74, 62, 88, 255)
LITE = (114, 98, 134, 255)
HI = (160, 142, 182, 255)
PURPLE = (207, 165, 255, 255)
CYAN = (138, 216, 255, 255)
GOLD = (255, 177, 78, 255)
WHITE = (255, 246, 224, 255)


def c(col, alpha=None):
    return col if alpha is None else (col[0], col[1], col[2], alpha)


class Art:
    def __init__(self, width: int, height: int | None = None):
        self.w, self.h = width, height or width
        self.image = Image.new("RGBA", (self.w * S, self.h * S), (0, 0, 0, 0))
        self.draw = ImageDraw.Draw(self.image, "RGBA")

    def box(self, x0, y0, x1, y1, fill=None, outline=None, width=1, radius=0):
        rect = (round(x0 * S), round(y0 * S), round(x1 * S), round(y1 * S))
        if radius:
            self.draw.rounded_rectangle(rect, radius=round(radius * S), fill=fill,
                                        outline=outline, width=max(1, round(width * S)))
        else:
            self.draw.rectangle(rect, fill=fill, outline=outline, width=max(1, round(width * S)))

    def line(self, points, fill, width=1):
        self.draw.line([(round(x * S), round(y * S)) for x, y in points], fill=fill,
                       width=max(1, round(width * S)), joint="curve")

    def ellipse(self, x0, y0, x1, y1, fill=None, outline=None, width=1):
        self.draw.ellipse((round(x0 * S), round(y0 * S), round(x1 * S), round(y1 * S)),
                          fill=fill, outline=outline, width=max(1, round(width * S)))

    def polygon(self, points, fill=None, outline=None, width=1):
        pts = [(round(x * S), round(y * S)) for x, y in points]
        self.draw.polygon(pts, fill=fill)
        if outline:
            self.draw.line(pts + [pts[0]], fill=outline, width=max(1, round(width * S)), joint="curve")

    def finish(self, glow=0.0):
        image = self.image.resize((self.w, self.h), Image.Resampling.LANCZOS)
        if glow > 0:
            # A restrained colored bloom, with alpha preserved for atlas packing.
            bloom = image.filter(ImageFilter.GaussianBlur(glow))
            image = Image.alpha_composite(bloom, image)
        return image


def save(art: Art, name: str, glow=0.0):
    path = OUT / f"{name}.png"
    art.finish(glow).save(path)
    print(f"  {path.name:27s} {art.w}x{art.h}")


def hexagon(cx, cy, r, angle=0.0):
    return [(cx + math.cos(math.radians(angle + i * 60)) * r,
             cy + math.sin(math.radians(angle + i * 60)) * r) for i in range(6)]


def tread_sheet(name: str, size: int, track_width: int, gap_left: int, pitch: int, glow_color):
    """Create a full two-track source sheet used by TankUnit's automatic slicer."""
    a = Art(size)
    positions = (gap_left, size - gap_left - track_width)
    for side, x in enumerate(positions):
        # The outer pixel must remain opaque from top to bottom: it is the animation sample column.
        a.box(x, 0, x + track_width - 1, size - 1, fill=OUTLINE)
        a.box(x + 1, 1, x + track_width - 2, size - 2, fill=DARK)
        # Alternating links; a moving 1px vertical source slice makes these visibly roll.
        for y in range(-pitch, size + pitch, pitch):
            a.box(x + 1, y + 1, x + track_width - 2, y + pitch - 2,
                  fill=MID if ((y // pitch) & 1) else LITE, outline=OUTLINE, width=.5, radius=1.0)
            a.line([(x + 2, y + 3), (x + track_width - 3, y + 3)], c(HI, 150), .55)
            a.line([(x + 2, y + pitch - 4), (x + track_width - 3, y + pitch - 4)], c(DARK, 220), .5)
        # Guide rollers and emissive service lights distinguish the Titan tracks from the support tank.
        for y in range(8, size, pitch * 2):
            rr = max(1.0, track_width * .13)
            a.ellipse(x + track_width * .5 - rr, y - rr, x + track_width * .5 + rr, y + rr,
                      fill=c(OUTLINE, 255), outline=c(HI, 110), width=.45)
            a.ellipse(x + track_width * .5 - rr * .35, y - rr * .35,
                      x + track_width * .5 + rr * .35, y + rr * .35, fill=c(glow_color, 220))
    save(a, name, glow=.45)


def citadel_body_parts():
    # Continuous body constraint array.
    a = Art(72)
    cx = cy = 36
    for r, col, alpha in ((31, PURPLE, 80), (25, CYAN, 180), (17, PURPLE, 210)):
        a.ellipse(cx-r, cy-r, cx+r, cy+r, outline=c(col, alpha), width=1.2)
    a.polygon(hexagon(cx, cy, 27, 30), outline=c(CYAN, 210), width=1.1)
    a.polygon(hexagon(cx, cy, 21, 0), outline=c(PURPLE, 185), width=.8)
    for i in range(6):
        angle = math.radians(i * 60 + 30)
        x, y = cx + math.cos(angle) * 29, cy + math.sin(angle) * 29
        a.ellipse(x-2, y-2, x+2, y+2, fill=c(CYAN, 245), outline=OUTLINE, width=.45)
    save(a, "citadel-array", glow=1.15)

    # Pulse at the center of the hull array.
    a = Art(42)
    for r, col, alpha in ((18, PURPLE, 45), (14, CYAN, 90), (10, PURPLE, 170)):
        a.ellipse(21-r, 21-r, 21+r, 21+r, fill=c(col, alpha))
    a.ellipse(9, 9, 33, 33, fill=(8, 6, 12, 255), outline=c(HI, 180), width=1)
    a.ellipse(13, 13, 29, 29, fill=c(PURPLE, 215), outline=c(CYAN, 235), width=.8)
    a.ellipse(17, 17, 25, 25, fill=WHITE)
    save(a, "citadel-core", glow=1.6)

    # One half of a rear armored hatch; RegionPart mirrors it and opens it on warmup.
    a = Art(40, 64)
    a.polygon([(5, 7), (35, 3), (38, 58), (10, 62), (3, 54)], fill=MID, outline=OUTLINE, width=1.1)
    a.polygon([(8, 10), (31, 7), (33, 24), (10, 27)], fill=LITE, outline=c(OUTLINE, 210), width=.65)
    a.box(10, 32, 33, 53, fill=DARK, outline=OUTLINE, width=.8, radius=2)
    for y in (36, 42, 48):
        a.line([(12, y), (30, y-2)], c(HI, 160), .7)
    a.box(7, 55, 34, 58, fill=c(PURPLE, 220), radius=.8)
    a.ellipse(26, 12, 31, 17, fill=CYAN, outline=OUTLINE, width=.5)
    save(a, "citadel-hatch", glow=.45)

    # Side armor panel that slides out very slightly with the hatch.
    a = Art(28, 46)
    a.polygon([(3, 4), (25, 1), (27, 40), (20, 45), (2, 41)], fill=MID, outline=OUTLINE, width=1)
    a.polygon([(6, 8), (22, 5), (24, 18), (7, 21)], fill=LITE, outline=c(OUTLINE, 200), width=.6)
    a.box(6, 27, 23, 36, fill=DARK, outline=OUTLINE, width=.65, radius=1.3)
    a.line([(7, 31), (21, 29)], c(PURPLE, 200), 1)
    a.ellipse(7, 38, 11, 42, fill=CYAN, outline=OUTLINE, width=.45)
    save(a, "citadel-armor", glow=.35)


def citadel_weapon_parts():
    # Main-gun ring: a centered transparent overlay, rotated continuously by RegionPart.
    a = Art(56)
    for r, col, alpha in ((25, PURPLE, 190), (20, GOLD, 220), (14, CYAN, 150)):
        a.ellipse(28-r, 28-r, 28+r, 28+r, outline=c(col, alpha), width=1.25)
    for i in range(8):
        ang = math.radians(i * 45)
        x, y = 28 + math.cos(ang) * 23, 28 + math.sin(ang) * 23
        a.box(x-2.4, y-2.4, x+2.4, y+2.4, fill=c(HI, 230), outline=OUTLINE, width=.45, radius=.7)
    save(a, "citadel-main-ring", glow=.85)

    # Single folding vent, mirrored by the gun animation definition.
    a = Art(24, 40)
    a.polygon([(3, 3), (21, 7), (19, 36), (5, 38)], fill=MID, outline=OUTLINE, width=.9)
    a.polygon([(6, 7), (18, 10), (17, 17), (7, 15)], fill=LITE, outline=c(OUTLINE, 180), width=.5)
    for y in (21, 26, 31):
        a.line([(7, y), (17, y+1)], c(HI, 165), .65)
    a.box(7, 34, 17, 36, fill=c(GOLD, 230), radius=.5)
    save(a, "citadel-main-vent", glow=.35)

    a = Art(28)
    for r, alpha in ((13, 42), (10, 90), (7, 180)):
        a.ellipse(14-r, 14-r, 14+r, 14+r, fill=c(GOLD, alpha))
    a.ellipse(6, 6, 22, 22, fill=(7, 5, 10, 245), outline=c(GOLD, 230), width=.8)
    a.ellipse(10, 10, 18, 18, fill=WHITE)
    save(a, "citadel-main-core", glow=1.4)

    # Fast AA targeting ring and slower side-gun reload ring.
    a = Art(32)
    a.ellipse(3, 3, 29, 29, outline=c(CYAN, 220), width=1.2)
    a.ellipse(7, 7, 25, 25, outline=c(PURPLE, 145), width=.8)
    for i in range(4):
        ang = math.radians(i * 90 + 45)
        x, y = 16 + math.cos(ang) * 12, 16 + math.sin(ang) * 12
        a.ellipse(x-1.8, y-1.8, x+1.8, y+1.8, fill=CYAN, outline=OUTLINE, width=.35)
    save(a, "citadel-aa-ring", glow=.8)

    a = Art(36)
    a.ellipse(3, 3, 33, 33, outline=c(PURPLE, 215), width=1.3)
    a.ellipse(8, 8, 28, 28, outline=c(GOLD, 190), width=1)
    for i in range(6):
        ang = math.radians(i * 60)
        x, y = 18 + math.cos(ang) * 13, 18 + math.sin(ang) * 13
        a.box(x-1.6, y-1.6, x+1.6, y+1.6, fill=c(GOLD, 230), outline=OUTLINE, width=.35, radius=.4)
    save(a, "citadel-side-ring", glow=.75)


def main():
    print("Generating Titan animation layers:")
    # Base sheets: only the left strip is sampled in BHUnits; TankUnit mirrors it.
    tread_sheet("citadel-treads", 232, 36, 0, 18, GOLD)
    tread_sheet("accretor-treads", 96, 19, 0, 13, PURPLE)
    citadel_body_parts()
    citadel_weapon_parts()
    print("Done.")


if __name__ == "__main__":
    main()
